# config.py

EXCEL_FILE_PATH = './All Quality Gold SKUs.xlsx'
QGOLD_SITE_URL = 'https://qgold.com/home'
EXTERNAL_DRIVE_PATH = './assets'
IMAGE_S3_BUCKET_NAME = 'YOUR-S3-BUCKET-NAME'
VIDEO_S3_BUCKET_NAME = 'YOUR-S3-BUCKET-NAME'
S3_BUCKET_NAME = 'YOUR-S3-BUCKET-NAME'
AWS_ACCESS_KEY = 'YOUR-AWS-ACCESS-KEY'
AWS_SECRET_KEY = 'YOUR-AWS-SECRET-KEY'
CHECKPOINT_FILE = 'checkpoints.json'